// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vira.DataAccess;

#nullable disable

namespace Vira.DataAccess.Migrations
{
    [DbContext(typeof(ViraDbContext))]
    [Migration("20260810144010_CreatorClipsSelected")]
    partial class CreatorClipsSelected
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Campaigns.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Campaigns.BusinessQuestionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AvoidsAlcohol")
                        .HasColumnType("boolean");

                    b.Property<bool>("AvoidsGambling")
                        .HasColumnType("boolean");

                    b.Property<bool>("AvoidsPolitical")
                        .HasColumnType("boolean");

                    b.Property<int>("BudgetBand")
                        .HasColumnType("integer");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<int>("CompanySize")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("CompetitorBrands")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrimaryGoal")
                        .HasColumnType("integer");

                    b.Property<string>("ProductsToPromote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("TargetAudienceAges")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<List<string>>("Values")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<int[]>("Verticals")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BusinessQuestionnaires");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Campaigns.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Budget")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Creators.ClipAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnalysisJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClipId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OntologyVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClipAnalyses");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Creators.Creator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<bool>("ClipsSelected")
                        .HasColumnType("boolean");

                    b.Property<string>("County")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FollowerCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Niche")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Creators");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Creators.CreatorClip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CommentCount")
                        .HasColumnType("bigint");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmbedLink")
                        .HasColumnType("text");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint");

                    b.Property<long>("ShareCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TikTokCreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TikTokVideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CreatorClips");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Creators.TikTokConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OpenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TikTokConnections");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Identity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirebaseUid")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Identity.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Campaigns.Campaign", b =>
                {
                    b.OwnsOne("Vira.Abstractions.Common.StyleVector", "TargetStyleVector", b1 =>
                        {
                            b1.Property<Guid>("CampaignId");

                            b1.Property<int>("Authority");

                            b1.Property<int>("Convention");

                            b1.Property<int>("Demonstration");

                            b1.Property<int>("Energy");

                            b1.Property<int>("Humor");

                            b1.Property<int>("Intimacy");

                            b1.Property<int>("Refinement");

                            b1.Property<int>("Warmth");

                            b1.HasKey("CampaignId");

                            b1.ToTable("Campaigns");

                            b1
                                .ToJson("TargetStyleVector")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId");
                        });

                    b.OwnsOne("Vira.Abstractions.Models.Campaigns.CampaignAccessRule", "AccessRule", b1 =>
                        {
                            b1.Property<Guid>("CampaignId");

                            b1.Property<long>("MinFollowerThreshold");

                            b1.Property<bool>("ProductPlacement");

                            b1.HasKey("CampaignId");

                            b1.ToTable("Campaigns");

                            b1
                                .ToJson("AccessRule")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId");
                        });

                    b.OwnsOne("Vira.Abstractions.Models.Campaigns.CampaignBrief", "Brief", b1 =>
                        {
                            b1.Property<Guid>("CampaignId");

                            b1.Property<string>("DurationPreset")
                                .IsRequired();

                            b1.Property<string>("ExtraRequirements")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Hashtags")
                                .IsRequired();

                            b1.Property<string>("Mention");

                            b1.Property<string>("Message")
                                .IsRequired();

                            b1.Property<int>("Objective");

                            b1.PrimitiveCollection<string>("Requirements")
                                .IsRequired();

                            b1.HasKey("CampaignId");

                            b1.ToTable("Campaigns");

                            b1
                                .ToJson("Brief")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId");
                        });

                    b.Navigation("AccessRule")
                        .IsRequired();

                    b.Navigation("Brief")
                        .IsRequired();

                    b.Navigation("TargetStyleVector")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
