// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vira.DataAccess;

#nullable disable

namespace Vira.DataAccess.Migrations
{
    [DbContext(typeof(ViraDbContext))]
    [Migration("20260812134034_AddSubmissionDecision")]
    partial class AddSubmissionDecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Campaigns.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Campaigns.BusinessQuestionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AvoidsAlcohol")
                        .HasColumnType("boolean");

                    b.Property<bool>("AvoidsGambling")
                        .HasColumnType("boolean");

                    b.Property<bool>("AvoidsPolitical")
                        .HasColumnType("boolean");

                    b.Property<int>("BudgetBand")
                        .HasColumnType("integer");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<int>("CompanySize")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("CompetitorBrands")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrimaryGoal")
                        .HasColumnType("integer");

                    b.Property<string>("ProductsToPromote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("TargetAudienceAges")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<List<string>>("Values")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<int[]>("Verticals")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BusinessQuestionnaires");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Campaigns.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Budget")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Campaigns.CampaignApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("DraftContent")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("DraftContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DraftFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DraftSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RejectionReason")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId", "CampaignId")
                        .IsUnique();

                    b.ToTable("CampaignApplications");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Creators.ClipAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnalysisJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClipId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OntologyVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClipAnalyses");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Creators.Creator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<bool>("ClipsSelected")
                        .HasColumnType("boolean");

                    b.Property<string>("County")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FollowerCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Niche")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Creators");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Creators.CreatorClip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CommentCount")
                        .HasColumnType("bigint");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmbedLink")
                        .HasColumnType("text");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint");

                    b.Property<long>("ShareCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TikTokCreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TikTokVideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CreatorClips");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Creators.CreatorPortrait", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExtensionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Limitations")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("NarrativeDossier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OntologyVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CreatorPortraits");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Creators.CreatorQuestionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AcceptsShippedProducts")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowsAlcohol")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowsGambling")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowsPolitical")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanPurchaseProducts")
                        .HasColumnType("boolean");

                    b.Property<int>("CollabCapacityPerMonth")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("ContentLanguages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("ExcludedBrands")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<int[]>("ExcludedCategories")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<List<string>>("Goals")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<int[]>("PreferredCategories")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<List<string>>("PreferredFormats")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SelfDescribedAudience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TravelWillingness")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Values")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("CreatorQuestionnaires");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Creators.PortraitRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("PortraitRequests");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Creators.TikTokConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OpenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TikTokConnections");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Identity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirebaseUid")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Identity.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Campaigns.Campaign", b =>
                {
                    b.OwnsOne("Vira.Abstractions.Common.StyleVector", "TargetStyleVector", b1 =>
                        {
                            b1.Property<Guid>("CampaignId");

                            b1.Property<double>("Authority");

                            b1.Property<double>("Convention");

                            b1.Property<double>("Demonstration");

                            b1.Property<double>("Energy");

                            b1.Property<double>("Humor");

                            b1.Property<double>("Intimacy");

                            b1.Property<double>("Refinement");

                            b1.Property<double>("Warmth");

                            b1.HasKey("CampaignId");

                            b1.ToTable("Campaigns");

                            b1
                                .ToJson("TargetStyleVector")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId");
                        });

                    b.OwnsOne("Vira.Abstractions.Models.Campaigns.CampaignAccessRule", "AccessRule", b1 =>
                        {
                            b1.Property<Guid>("CampaignId");

                            b1.Property<long>("MinFollowerThreshold");

                            b1.Property<bool>("ProductPlacement");

                            b1.HasKey("CampaignId");

                            b1.ToTable("Campaigns");

                            b1
                                .ToJson("AccessRule")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId");
                        });

                    b.OwnsOne("Vira.Abstractions.Models.Campaigns.CampaignBrief", "Brief", b1 =>
                        {
                            b1.Property<Guid>("CampaignId");

                            b1.Property<string>("DurationPreset")
                                .IsRequired();

                            b1.Property<string>("ExtraRequirements")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Hashtags")
                                .IsRequired();

                            b1.Property<string>("Mention");

                            b1.Property<string>("Message")
                                .IsRequired();

                            b1.Property<int>("Objective");

                            b1.PrimitiveCollection<string>("Requirements")
                                .IsRequired();

                            b1.HasKey("CampaignId");

                            b1.ToTable("Campaigns");

                            b1
                                .ToJson("Brief")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId");
                        });

                    b.Navigation("AccessRule")
                        .IsRequired();

                    b.Navigation("Brief")
                        .IsRequired();

                    b.Navigation("TargetStyleVector")
                        .IsRequired();
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Creators.CreatorPortrait", b =>
                {
                    b.OwnsOne("Vira.Abstractions.Common.StyleVector", "StyleVector", b1 =>
                        {
                            b1.Property<Guid>("CreatorPortraitId");

                            b1.Property<double>("Authority");

                            b1.Property<double>("Convention");

                            b1.Property<double>("Demonstration");

                            b1.Property<double>("Energy");

                            b1.Property<double>("Humor");

                            b1.Property<double>("Intimacy");

                            b1.Property<double>("Refinement");

                            b1.Property<double>("Warmth");

                            b1.HasKey("CreatorPortraitId");

                            b1.ToTable("CreatorPortraits");

                            b1
                                .ToJson("StyleVector")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CreatorPortraitId");
                        });

                    b.OwnsOne("Vira.Abstractions.Models.Creators.StyleEvidence", "StyleEvidence", b1 =>
                        {
                            b1.Property<Guid>("CreatorPortraitId");

                            b1.HasKey("CreatorPortraitId");

                            b1.ToTable("CreatorPortraits");

                            b1
                                .ToJson("StyleEvidence")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CreatorPortraitId");

                            b1.OwnsOne("Vira.Abstractions.Models.Creators.DimensionEvidence", "Authority", b2 =>
                                {
                                    b2.Property<Guid>("StyleEvidenceCreatorPortraitId");

                                    b2.Property<double>("Confidence");

                                    b2.PrimitiveCollection<string>("EvidenceClipIds")
                                        .IsRequired();

                                    b2.Property<string>("Rationale")
                                        .IsRequired();

                                    b2.HasKey("StyleEvidenceCreatorPortraitId");

                                    b2.ToTable("CreatorPortraits");

                                    b2.WithOwner()
                                        .HasForeignKey("StyleEvidenceCreatorPortraitId");
                                });

                            b1.OwnsOne("Vira.Abstractions.Models.Creators.DimensionEvidence", "Convention", b2 =>
                                {
                                    b2.Property<Guid>("StyleEvidenceCreatorPortraitId");

                                    b2.Property<double>("Confidence");

                                    b2.PrimitiveCollection<string>("EvidenceClipIds")
                                        .IsRequired();

                                    b2.Property<string>("Rationale")
                                        .IsRequired();

                                    b2.HasKey("StyleEvidenceCreatorPortraitId");

                                    b2.ToTable("CreatorPortraits");

                                    b2.WithOwner()
                                        .HasForeignKey("StyleEvidenceCreatorPortraitId");
                                });

                            b1.OwnsOne("Vira.Abstractions.Models.Creators.DimensionEvidence", "Demonstration", b2 =>
                                {
                                    b2.Property<Guid>("StyleEvidenceCreatorPortraitId");

                                    b2.Property<double>("Confidence");

                                    b2.PrimitiveCollection<string>("EvidenceClipIds")
                                        .IsRequired();

                                    b2.Property<string>("Rationale")
                                        .IsRequired();

                                    b2.HasKey("StyleEvidenceCreatorPortraitId");

                                    b2.ToTable("CreatorPortraits");

                                    b2.WithOwner()
                                        .HasForeignKey("StyleEvidenceCreatorPortraitId");
                                });

                            b1.OwnsOne("Vira.Abstractions.Models.Creators.DimensionEvidence", "Energy", b2 =>
                                {
                                    b2.Property<Guid>("StyleEvidenceCreatorPortraitId");

                                    b2.Property<double>("Confidence");

                                    b2.PrimitiveCollection<string>("EvidenceClipIds")
                                        .IsRequired();

                                    b2.Property<string>("Rationale")
                                        .IsRequired();

                                    b2.HasKey("StyleEvidenceCreatorPortraitId");

                                    b2.ToTable("CreatorPortraits");

                                    b2.WithOwner()
                                        .HasForeignKey("StyleEvidenceCreatorPortraitId");
                                });

                            b1.OwnsOne("Vira.Abstractions.Models.Creators.DimensionEvidence", "Humor", b2 =>
                                {
                                    b2.Property<Guid>("StyleEvidenceCreatorPortraitId");

                                    b2.Property<double>("Confidence");

                                    b2.PrimitiveCollection<string>("EvidenceClipIds")
                                        .IsRequired();

                                    b2.Property<string>("Rationale")
                                        .IsRequired();

                                    b2.HasKey("StyleEvidenceCreatorPortraitId");

                                    b2.ToTable("CreatorPortraits");

                                    b2.WithOwner()
                                        .HasForeignKey("StyleEvidenceCreatorPortraitId");
                                });

                            b1.OwnsOne("Vira.Abstractions.Models.Creators.DimensionEvidence", "Intimacy", b2 =>
                                {
                                    b2.Property<Guid>("StyleEvidenceCreatorPortraitId");

                                    b2.Property<double>("Confidence");

                                    b2.PrimitiveCollection<string>("EvidenceClipIds")
                                        .IsRequired();

                                    b2.Property<string>("Rationale")
                                        .IsRequired();

                                    b2.HasKey("StyleEvidenceCreatorPortraitId");

                                    b2.ToTable("CreatorPortraits");

                                    b2.WithOwner()
                                        .HasForeignKey("StyleEvidenceCreatorPortraitId");
                                });

                            b1.OwnsOne("Vira.Abstractions.Models.Creators.DimensionEvidence", "Refinement", b2 =>
                                {
                                    b2.Property<Guid>("StyleEvidenceCreatorPortraitId");

                                    b2.Property<double>("Confidence");

                                    b2.PrimitiveCollection<string>("EvidenceClipIds")
                                        .IsRequired();

                                    b2.Property<string>("Rationale")
                                        .IsRequired();

                                    b2.HasKey("StyleEvidenceCreatorPortraitId");

                                    b2.ToTable("CreatorPortraits");

                                    b2.WithOwner()
                                        .HasForeignKey("StyleEvidenceCreatorPortraitId");
                                });

                            b1.OwnsOne("Vira.Abstractions.Models.Creators.DimensionEvidence", "Warmth", b2 =>
                                {
                                    b2.Property<Guid>("StyleEvidenceCreatorPortraitId");

                                    b2.Property<double>("Confidence");

                                    b2.PrimitiveCollection<string>("EvidenceClipIds")
                                        .IsRequired();

                                    b2.Property<string>("Rationale")
                                        .IsRequired();

                                    b2.HasKey("StyleEvidenceCreatorPortraitId");

                                    b2.ToTable("CreatorPortraits");

                                    b2.WithOwner()
                                        .HasForeignKey("StyleEvidenceCreatorPortraitId");
                                });

                            b1.Navigation("Authority")
                                .IsRequired();

                            b1.Navigation("Convention")
                                .IsRequired();

                            b1.Navigation("Demonstration")
                                .IsRequired();

                            b1.Navigation("Energy")
                                .IsRequired();

                            b1.Navigation("Humor")
                                .IsRequired();

                            b1.Navigation("Intimacy")
                                .IsRequired();

                            b1.Navigation("Refinement")
                                .IsRequired();

                            b1.Navigation("Warmth")
                                .IsRequired();
                        });

                    b.Navigation("StyleEvidence")
                        .IsRequired();

                    b.Navigation("StyleVector")
                        .IsRequired();
                });

            modelBuilder.Entity("Vira.Abstractions.Models.Creators.CreatorQuestionnaire", b =>
                {
                    b.OwnsMany("Vira.Abstractions.Models.Creators.PriorSponsorship", "PriorSponsorships", b1 =>
                        {
                            b1.Property<Guid>("CreatorQuestionnaireId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("BrandName")
                                .IsRequired();

                            b1.Property<int>("Category");

                            b1.HasKey("CreatorQuestionnaireId", "__synthesizedOrdinal");

                            b1.ToTable("CreatorQuestionnaires");

                            b1
                                .ToJson("PriorSponsorships")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CreatorQuestionnaireId");
                        });

                    b.Navigation("PriorSponsorships");
                });
#pragma warning restore 612, 618
        }
    }
}
